theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
twitter:
  username: narisada014
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /static/images/thumbnail.jpg
        height: 125
        width: 125
